development: &default
  adapter: postgresql
  encoding: unicode
  database: woodsey_reference
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: woodsey_reference_test
